### ISSUE TITLE
Suggestion: Is this only for endpoints, or can a relay device be helpful and send these on the client's behalf?

### ISSUE THREAD

**Issue by wkumari** [wkumari/draft-wkumari-dhc-addr-notification#32] opened 2023-02-28 00:00 UTC
If we do this, just like for the serve ACK, we need to clarify that this is **just** informational -- the switch is helpfully telling the server that a client is using an address, but it MUST NOT block the message from the client, it MUST NOT use this for access control, etc.

**Comment by wkumari** [comment] 2023-02-28 00:13
This seems like it might be quite complex, as it will likely require devices to spoof the global address. I think better to skip it for now? 

Ack: Eric Vynke

**Comment by furry13** [comment] 2023-02-28 21:26
It looks like a duplicate of https://github.com/wkumari/draft-wkumari-dhc-addr-notification/issues/9

**Comment by lcolitti** [comment] 2023-03-30 06:20
Duplicate of #9 .

**Closed by lcolitti** 2023-03-30 06:20 UTC
